---
- name: Open firewall ports
  firewalld:
    immediate: yes
    permanent: yes
    port: "{{item.port}}/{{item.proto}}"
    state: "{{item.state}}"
    zone: "{{zone_default}}"
  with_items:
    - { port: "22", proto: "tcp", state: "enabled" }
    - { port: "80", proto: "tcp", state: "enabled" }
    - { port: "443", proto: "tcp", state: "enabled" }
    - { port: "53", proto: "udp", state: "enabled" }
    - { port: "8472", proto: "udp", state: "enabled" }
    - { port: "10250", proto: "tcp", state: "enabled" }
    - { port: "30000-32767", proto: "tcp", state: "enabled" }

- name: Enable Masquerading
  firewalld:
    masquerade: yes
    state: enabled
    permanent: yes
    immediate: yes
    zone: "{{ zone_default }}"

- name: Install iptables-services
  dnf:
    name: iptables-services
    state: present

- name: Copy K3s service file
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s-node.service"
    owner: root
    group: root
    mode: 0755

- name: Enable and check K3s service
  systemd:
    name: k3s-node
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Add interfaces to trusted zone
  firewalld:
    immediate: yes
    interface: "{{ item }}"
    permanent: yes
    state: enabled
    zone: trusted
  with_items:
    - cni0
    - flannel.1

- name: Allow VXLAN and K3s ports in FedoraServer zone
  firewalld:
    immediate: yes
    permanent: yes
    port: "{{ item }}"
    state: enabled
    zone: "{{ zone_default }}"
  with_items:
    - "8472/udp"   # Flannel VXLAN
    - "10250/tcp"  # Kubelet
    - "6443/tcp"   # API Server