---
- name: Open firewall ports for K3s and Web Traffic
  firewalld:
    immediate: yes
    permanent: yes
    port: "{{ item.port }}/{{ item.proto }}"
    state: "{{ item.state }}"
    zone: "{{ zone_default }}"
  loop:
    - { port: "22", proto: "tcp", state: "enabled" }
    - { port: "80", proto: "tcp", state: "enabled" }     # Standard HTTP
    - { port: "443", proto: "tcp", state: "enabled" }    # Standard HTTPS
    - { port: "6443", proto: "tcp", state: "enabled" }   # K3s API
    - { port: "2376", proto: "tcp", state: "enabled" }
    - { port: "8472", proto: "udp", state: "enabled" }   # Flannel VXLAN
    - { port: "9099", proto: "tcp", state: "enabled" }
    - { port: "10250", proto: "tcp", state: "enabled" }  # Kubelet
    - { port: "10254", proto: "tcp", state: "enabled" }
    - { port: "30000-32767", proto: "tcp", state: "enabled" } # NodePorts
    - { port: "30000-32767", proto: "udp", state: "enabled" }

- name: Enable Masquerading
  firewalld:
    masquerade: yes
    state: enabled
    permanent: yes
    immediate: yes
    zone: "{{ zone_default }}"

- name: Add interfaces to trusted zone
  firewalld:
    immediate: yes
    interface: "{{ item }}"
    permanent: yes
    state: enabled
    zone: trusted
  loop:
    - cni0
    - flannel.1

- name: Copy K3s service file
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s-node.service"
    owner: root
    group: root
    mode: "0755"

- name: Enable and check K3s service
  systemd:
    name: k3s-node
    daemon_reload: yes
    state: restarted
    enabled: yes