---

- name: Open firewall ports
  firewalld:
    immediate: yes
    permanent: yes
    port: "{{item.port}}/{{item.proto}}"
    state: "{{item.state}}"
    zone: "{{zone_default}}"
  with_items:
  - {port: "22", proto: "tcp", state: "enabled"}
  - {port: "80", proto: "tcp", state: "enabled"}
  - {port: "443", proto: "tcp", state: "enabled"}
  - {port: "2376", proto: "tcp", state: "enabled"}  
  - {port: "8472", proto: "udp", state: "enabled"}
  - {port: "9099", proto: "tcp", state: "enabled"}
  - {port: "10250", proto: "tcp", state: "enabled"}
  - {port: "10254", proto: "tcp", state: "enabled"}
  - {port: "30000-32767", proto: "tcp", state: "enabled"}
  - {port: "30000-32767", proto: "udp", state: "enabled"}

- name: Add cni0 to trusted zone
  firewalld:
    immediate: yes
    interface: cni0
    permanent: yes
    state: enabled
    zone: trusted

- name: Copy K3s service file
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s-node.service"
    owner: root
    group: root
    mode: 0755

- name: Enable and check K3s service
  systemd:
    name: k3s-node
    daemon_reload: yes
    state: restarted
    enabled: yes
