---
- name: Copy K3s service file
  template:
    src: "../../templates/k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s-node.service"
    owner: root
    group: root
    mode: 0755
  notify: restart k3s-node

- name: Enable and check K3s service
  systemd:
    name: k3s-node
    daemon_reload: yes
    state: started
    enabled: yes  

- name: Add interfaces to trusted zone
  ignore_errors: true
  firewalld:
    immediate: yes
    interface: "{{ item }}"
    permanent: yes
    state: enabled
    zone: trusted
  with_items:
    - cni0
    - flannel.1