---
argocd_namespace: argocd
argocd_chart_version: "9.4.2"
gitops_repo_url: "https://github.com/TheBatchelorFamily/HomeInfra.git"
gitops_repo_path: "argocd-apps"
gitops_repo_branch: "main"
argocd_app_path: "gitops/argocd-apps"
