---
k3s_version: v1.35.0+k3s1
ansible_user: chris
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: ""
extra_agent_args: ""
zone_default: "FedoraServer"